functional:
  - Режим дуэли между двумя игроками с live-отображением кода
  - Поддержка нескольких языков программирования (Python, JavaScript, Haskell, Java, Ruby, PHP)
  - Система рейтинга (ELO - алгоритм расчёта рейтинга используемый в соревновательных играх)
  - Лидерборд (таблица лидеров, отображающая топ игроков по рейтингу)
  - Режим тренировки против бота (AI с разными уровнями сложности - Easy, Medium, Hard)
  - Приватные игры по ссылке (custom games — создание закрытой комнаты для игры с другом)
  - Возможность создавать и добавлять новые задачи (для администраторов и других "доверенных" пользователей)
  - Турнирный режим 
  - Интеграция с GitHub для аутентификации (вход через аккаунт GitHub)
  - Чат во время игры 
  - Подсказки и проверка решений в реальном времени (автоматический тестинг кода)

non-functional:
  - Низкие задержки при взаимодействии (WebSocket — технология для обмена данными в реальном времени)
  - Защита данных (OAuth — протокол авторизации через GitHub, HTTPS)
  - Адаптивный интерфейс (корректное отображение на ПК, и мобильных устройствах)
  - Поддержка современных браузеров (Chrome, Firefox, Safari, Edge)
  - Масштабируемость (использование Phoenix/Elixir — фреймворка для высоконагруженных приложений)
  - Логирование и мониторинг ошибок (Sentry — система отслеживания ошибок в production-среде)
  - CI/CD (Continuous Integration / Continuous Deployment — автоматизированные тесты и деплой)

implicit:
  - Открытый исходный код (open-source проект на GitHub)
  - Гибкий процесс развития с учётом предложений сообщества (обсуждения в Telegram-чате)
  - Умеренная модерация пользовательского контента (возможность предложить задачу с последующей проверкой)
  - Поддержка игроков разного уровня подготовки (от новичков до экспертов)
  - Наличие документации для разработчиков (инструкции по развёртыванию)
